# Game window 
GAME_TITLE = 'SOS'
RESOLUTION_WIDTH = 800
RESOLUTION_HEIGHT = 600
GAME_FPS = 60
BACKGROUND_COLOUR = (255, 255, 255)

# Play button
PLAY_BUTTON_W = 175
PLAY_BUTTON_H = 100
PLAY_BUTTON_X = int(RESOLUTION_WIDTH / 2 - PLAY_BUTTON_W / 2)
PLAY_BUTTON_Y = int(RESOLUTION_HEIGHT / 2 - PLAY_BUTTON_H)
PLAY_BUTTON_TEXT = 'PLAY VS AI'
PLAY_BUTTON_COLOUR = (39, 186, 78)
PLAY_BUTTON_TEXT_COLOUR = (45, 51, 47)

# Unit game cell
GAME_CELL_W = 50
GAME_CELL_H = GAME_CELL_W
GAME_GRID_W = 7
GAME_GRID_H = GAME_GRID_W


# Score Objects
PLAYER_SCORE_BOX_W = 150
PLAYER_SCORE_BOX_H = 25
PLAYER_SCORE_BOX_X = int(RESOLUTION_WIDTH / 3 - PLAYER_SCORE_BOX_W / 2)
PLAYER_SCORE_BOX_Y = 0
PLAYER_SCORE_BOX_COLOUR = BACKGROUND_COLOUR
PLAYER_SCORE_BOX_TEXT = 'PLAYER: '
PLAYER_COLOUR = (181, 32, 5)

AI_SCORE_BOX_W = PLAYER_SCORE_BOX_W
AI_SCORE_BOX_H = PLAYER_SCORE_BOX_H
AI_SCORE_BOX_X = int(2 * RESOLUTION_WIDTH / 3 - PLAYER_SCORE_BOX_W / 2)
AI_SCORE_BOX_Y = PLAYER_SCORE_BOX_Y
AI_SCORE_BOX_COLOUR = BACKGROUND_COLOUR
AI_SCORE_BOX_TEXT = 'AI: '
AI_COLOUR = (13, 35, 161)